openapi: 3.0.0
info:
  title: Users
  version: '1.0'
servers:
  - url: 'https://stoplight.io/v1/users'
paths:
  /users:
    get:
      summary: Returns list of the users
      tags:
        - Users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  id:
                    type: number
                  age:
                    type: number
                  phone:
                    type: string
                required:
                  - name
                  - id
                  - age
                  - phone
              examples:
                example-1:
                  value:
                    name: test
                    id: 1
                    age: 1
                    phone: '234234234'
      operationId: get-users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: number
                age:
                  type: number
                phone:
                  type: string
              required:
                - name
                - id
                - age
                - phone
            examples:
              example-1:
                value:
                  name: test
                  id: 1
                  age: 1
                  phone: '234234234'
          application/xml:
            schema:
              type: object
              properties: {}
        description: OK
      description: ''
components:
  schemas: {}
  securitySchemes: {}
